### ISSUE TITLE
Re-enable CI for "Integration tests" once InstaWP environment is properly setup

### ISSUE THREAD

**Issue by leoloso** [GatoGraphQL/GatoGraphQL#2253]
The CI executes Integration tests for PROD by pointing to an InstaWP instance. However, as there is no WP-CLI support in this plan, the environment cannot be easily setup, and these Integration Tests are always failing.

So this CI execution has been temporarily commented out, as there's no point in executing it (and showing a failing badge).

Re-enable it as soon as the InstaWP environment is properly setup (whether by having access to WP-CLI, or doing it manually). For that, uncomment the code that has this snippet (in `.php` or `.md` or `.yml` files):

```
@todo Re-enable executing integration tests for PROD in CI
```

**Comment by leoloso** [comment]
Whenever fixed, modify again workflow `.github/workflows/integration_tests.yml`, with this code:

```yaml
name: Integration tests
on:
    workflow_run:
        workflows: [Generate plugins]
        types:
            - completed
```
